config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'posts#index'

    resources :posts do
      resources :comments, only: %i[create destroy]

      collection do
        post 'attachment_create'
      end
    end

    resources :categories
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true

  enum anonymous: {
    inactive: 0,
    active: 1
  }

  def anonymous=(value)
    self[:anonymous] = value.to_i
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.comments.create(permitted_params.to_h.merge!({ user_id: current_user.id }))
    redirect_to post_path(@post), notice: t('app.create.success', model: Comment.model_name.human)
  end

  def destroy
    comment = @post.comments.find(params[:id])
    authorize comment

    comment.destroy
    redirect_to post_path(@post), notice: t('app.destroy.success', model: Comment.model_name.human)
  end

  private

  def permitted_params
    params.require(:comment).permit(:body, :anonymous)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= month_day_comma_year(comment.created_at) %></h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <%= t('comments.index.author') %>: <%= comment.anonymous == 'active' ? t('comments.index.anonymous') : sub_masked_email(comment.user.email) %>
    </h6>
    <p class="card-text"><%= comment.body %></p>
    <%= link_to 'Destroy', post_comment_path(@post, comment),
      method: :delete,
      data: { confirm: t('app.message.confirm_destroy') },
      class: 'btn btn-danger' if policy(comment).destroy? %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @post.comments.build] do |f| %>
  <div class="form-inputs">
    <%= f.input :body, input_html: { rows: 10 } %>
  </div>

  <%= f.input :anonymous, as: :boolean, label: t('comments.index.commenter')  %>

  <div class="form-action">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>