config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'posts#index'

    resources :posts do
      resources :comments, only: %i[create destroy]

      collection do
        post 'attachment_create'
      end
    end

    resources :categories
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include PostScopes

  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_one_attached :attachment_file

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }

  paginates_per 3
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[edit update destroy]
  before_action :set_categories, only: %i[index new create edit update]
  
  def index
    @archives = Post.group_by_month(:created_at, format: '%B %Y', locale: :en).count
  
    category = @categories.find { |c| c.name == params[:category] } if params[:category].present?
    month_year = @archives.find { |m| m[0] == params[:month_year] }&.first if params[:month_year].present?

    @highlights = Post.includes(:category, :user)
                      .filter_by_category(category)
                      .filter_by_archive(month_year)
                      .asc_order
                      .first(3)

    highlight_ids = @highlights.pluck(:id).join(',')

    @posts = Post.includes(:category, :user)
                 .without_highlights(highlight_ids)
                 .filter_by_category(category)
                 .filter_by_archive(month_year)
                 .desc_order
                 .page(current_page)
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])

    if @post.nil?
      redirect_to new_post_path, alert: t('helpers.select.prompt')
    else
      authorize @post
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(permitted_params)

    if @post.save
      redirect_to @post, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(permitted_params)
      redirect_to @post, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @post.destroy

    redirect_to root_path, notice: t('.success')
  end

  def attachment_create
    file = params[:post][:attachment_file]
    category_id = params[:post][:category_id]
  
    if file
      file_path = Rails.root.join('tmp', file.original_filename)
      File.open(file_path, 'wb') do |f|
        f.write(file.read)
      end
  
      ProcessPostJob.perform_later(current_user.id, file_path.to_s, category_id)
      
      redirect_to root_path, notice: t('.success')
    else
      redirect_to new_post_path, alert: t('helpers.select.prompt')
    end
  end

  private

  def permitted_params
    params.require(:post).permit(:title, :description, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def set_categories
    @categories = Category.sorted
  end
end

app/views/posts/_archives.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'posts.archives' %></h4>
  <ol class="list-unstyled mb-0">
    <% @archives.each do |month_year, count| %>
      <li>
        <%= link_to "#{month_year(month_year)} (#{count})", posts_path(month_year: month_year),
            class: "p-2 btn-link #{'filter-active' if month_year == params[:month_year]}" %>
      </li>
    <% end %>
  </ol>
</div>

app/views/posts/_attachment_new.html.erb
<%= form_with model: @post, url: attachment_create_posts_path, method: :post, local: true, enctype: 'multipart/form-data' do |form| %>

  <p><%= t('posts.attachment.body') %></p>
  <p><%= t('posts.attachment.description') %></p>
  <p><%= t('posts.attachment.structure.title')+' | '+t('posts.attachment.structure.description') %></p>
  <p><%= t('posts.attachment.structure.title')+' | '+t('posts.attachment.structure.description') %></p>
  <p><%= t('posts.attachment.structure.title')+' | '+t('posts.attachment.structure.description') %></p>

  <%= form.label :attachment_file, 'Upload TXT' %>
  <%= form.file_field :attachment_file %>

  <%= form.label :category_id, t('app.menu.categories')+':' %>
  <%= form.collection_select :category_id, @categories, :id, :name %>

  <%= form.submit 'Enviar' %>
<% end %>

app/views/posts/_elsewhere.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'posts.elsewhere' %></h4>
  <ol class="list-unstyled">
    <li><a href="https://github.com/felipe-salomao" target="_blank">GitHub</a></li>
    <li><a href="https://www.linkedin.com/in/felipens12/">Linkedin</a></li>
    <li><a href="https://www.instagram.com/fpliipe/">Instagram</a></li>
  </ol>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description, input_html: { rows: 10 } %>
    <%= f.association :category, collection: @categories, prompt: t('posts.form.choose_category') %>
  </div>

  <div class="form-action">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to t('app.button.back'), root_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/posts/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic"><%= post.title %></h1>
    <p class="lead my-3"><%= truncate(post.description, length: 100) %></p>
    <p class="lead mb-0">
      <%= link_to t('posts.continue_reading'), post, class: 'text-white fw-bold' %>
    </p>
  </div>
</div>

app/views/posts/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">
        <%= post.category.name %>
      </strong>

      <h3 class="mb-0"><%= post.title %></h3>

      <div class="mb-1 text-muted">
        <%= render 'post_detail', post: post %>
      </div>

      <p class="card-text mb-auto">
        <%= truncate(post.description, length: 100) %>
      </p>

      <%= link_to t('posts.continue_reading'), post, class: 'stretched-link' %>
    </div>

    <div class="col-auto d-none d-lg-block">
      <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

    </div>
  </div>
</div>

app/views/posts/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
  <%= link_to_next_page @posts, t('app.pagination.next'), class: 'btn btn-outline-primary' %>
  <%= link_to_previous_page @posts, t('app.pagination.previous'), class: 'btn btn-outline-primary' %>
</nav>

app/views/posts/_post.html.erb
<article class="blog-post">
  <strong class="d-inline-block mb-2 text-primary">
    <%= post.category.name %>
  </strong>

  <h2 class="blog-post-title"><%= post.title %></h2>

  <p class="blog-post-meta">
    <%= render 'post_detail', post: post %>
  </p>

  <p><%= truncate(post.description, length: 150) %></p>

  <p><%= link_to t('posts.continue_reading'), post, class: 'btn btn-link' %></p>

  <%= link_to t('app.button.edit'), edit_post_path(post), class: 'btn btn-primary' if policy(post).update? %>
  <%= link_to t('app.button.destroy'), post_path(post),
    method: :delete,
    data: { confirm: t('app.message.confirm_destroy') },
    class: 'btn btn-danger' if policy(post).destroy? %>
</article>

app/views/posts/_post_detail.html.erb
<%= month_day_comma_year(post.created_at) %>  <%= t('app.word.by') %>
<%= sub_masked_email(post.user.email) %>

app/views/posts/_right_side.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <%= render 'about' %>
    <%= render 'archives' %>
    <%= render 'elsewhere' %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1><%= t('app.edit.title', model: Post.model_name.human) %></h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured', post: @highlights[0] %>

<div class="row mb-2">
  <%= render_if @highlights[1].present?, 'medium_featured', post: @highlights[1] %>
  <%= render_if @highlights[2].present?, 'medium_featured', post: @highlights[2] %>
</div>

<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      <%= t '.subtitle' %>
    </h3>

    <p>
      <%= link_to t('posts.new.title'), new_post_path, class: 'btn btn-success' if user_signed_in? %>
    </p>

    <%= render @posts %>
    <%= render 'pagination' %>
  </div>

  <%= render 'right_side' %>
</div>

<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, posts_path(category: category.name),
            class: "p-2 link-secondary #{'filter-active' if category.name.to_s == params[:category]}" %>
      <% end %>
    </nav>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1><%= t '.title' %></h1>

<div class="blog-post">
  <%= render 'form', post: @post %>
</div>

<%= render 'attachment_new' %>

app/views/posts/show.html.erb
<article class="blog-post">
  <strong class="d-inline-block mb-2 text-primary">
    <%= @post.category.name %>
  </strong>

  <h2 class="blog-post-title"><%= @post.title %></h2>

  <p class="blog-post-meta">
    <%= render 'post_detail', post: @post %>
  </p>

  <p><%= @post.description %></p>

  <%= link_to t('app.button.edit'), edit_post_path(@post), class: 'btn btn-primary' if policy(@post).update? %>

  <%= link_to t('app.button.destroy'), post_path(@post),
    method: :delete,
    data: { confirm: t('app.message.confirm_destroy') },
    class: 'btn btn-danger' if policy(@post).destroy? %>

  <%= link_to t('app.button.back'), root_path, class: 'btn btn-secondary' %>

  <h2 class="mt-3"><%= t('.comments') %></h2>
  <%= render @post.comments %>

  <h3><%= t('.add_comment') %></h3>
  <% if policy(:comment).create? %>
    <%= render 'comments/form' %>
  <% else %>
    <%= t('.login_create_comment') %>
  <% end %>
</article>